name: env_qlib
channels:
  - defaults

dependencies:
- python=3.11
- numpy
- numba
- pandas
- scipy
- matplotlib
- pip
- pip:
  - omegaconf
  - loguru
  - black
  - ruff
  - xarray
  - pytest
  - jupyterlab
  - ipython
  - ipykernel
  - -e .